name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #  uses: cypress-io/github-action@v2
      #  env:
      #    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #    # Recommended: pass the GitHub token lets this action correctly
      #    # determine the unique run id necessary to re-run the checks
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    build: npm run build
      #    start: npm start

      - name: Testing
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          npm ci
          npm run build
          npm run start &
          npx cypress run --record --headless